config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # get '/todos', to: 'todos#index'
  # get 'todos/new', to: 'todos#new'
  # get '/todos/:id', to: 'todos#show'
  # get '/todos/:id/edit', to: 'todos#edit'
  # post '/todos', to: 'todos#create'
  # put '/todos', to: 'todos#update'
  # delete '/todos', to: 'todos#destroy'

  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	validates_presence_of :body
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def new
		@todo = Todo.new
		@date = Date.today.to_s
	end

	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			redirect_to todo_path(@todo)
		else
			render :new
		end 
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update_attributes(todo_params)
			redirect_to todo_path(@todo)
		else
			render :new
		end 
	end

	def destroy
		@todo = Todo.find(params[:id])
		if @todo.destroy
			redirect_to '/'
		else
			redirect_to todos_path(@todo)
		end
	end

	private 

	def todo_params
		params.require(:todo).permit(:body, :date)
	end
end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@date = Date.today.to_formatted_s(:long_ordinal)
		@friday = Time.now.strftime("%A") == 'Friday'
		@today = Time.now.strftime("%A")
		@todos = Todo.where(date: Date.today.to_s)
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2><%= link_to 'home', '/' %> </h2>
<h2> <%= link_to 'all todos', todos_path %>  </h2>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<%= form_for @todo do |f|%>
<%= f.text_field :body, value: @todo.body %> 
<%= f.submit %> 
<% end %>

app/views/todos/index.html.erb
<ul>
	<% @todos.each do |todo| %>
	<li> <%= todo.body %> <span> written <%= time_ago_in_words(todo.created_at) %> ago </span> </li>
	<% end %> 
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |f|%>
<%= f.hidden_field :date, value: @date %> 
<%= f.text_field :body, placeholder: 'enter task' %>
<%= f.submit %> 
<% end %>  

app/views/todos/show.html.erb
<p> <%= @todo.body %> </p>

app/views/welcome/index.html.erb
<h1> Hello world! <span>It is <%= @date %> </span></h1>
<% if @friday %>
	<h2> It is Friday!!! </h2>
<% else %>  
	<h2> Not Friday just yet. It's only <%= @today %> :( </h2>
<% end %> 

<h3> Today's todos </h2>
<ul>
<% @todos.each do |todo| %>
	<li><%= todo.body %> <span> <%= link_to 'x', todo_path(todo), method: 'delete' %> <%= link_to 'edit', edit_todo_path(todo) %> </span> </li>
<% end %>  
</ul>
<button><a href="/todos/new">Add task</a></button>